<?php

namespace Andrewlamers\EloquentRestBridge\Connections;

use Andrewlamers\EloquentRestBridge\Request\Request;
use \Illuminate\Encryption\Encrypter;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

trait ConnectionTrait
{
    protected $http;
    protected $connector;
    protected $lastInsertId;

    public function __construct($pdo, $database = '', $tablePrefix = '', array $config = [])
    {
        $this->http = new Request($config);
        $this->config = $config;

        parent::__construct($pdo, $database, $tablePrefix, $config);
    }

    public function sendRequest($query, $bindings, $type)
    {

        $data = [
            'query'    => $query,
            'bindings' => $bindings,
            'config'   => $this->config,
            'type'     => $type
        ];

        $data = $this->http->request($data);

        if (count($data['results']) < 1) {
            return NULL;
        }

        return $data['results'];
    }

    public function select($query, $bindings = [], $useReadPdo = TRUE)
    {
        return $this->sendRequest($query, $bindings, "select");
        //return parent::select($query, $bindings, $useReadPdo); // TODO: Change the autogenerated stub
    }

    public function update($query, $bindings = [])
    {
        return $this->sendRequest($query, $bindings, "update");
        //return parent::update($query, $bindings); // TODO: Change the autogenerated stub
    }

    public function delete($query, $bindings = [])
    {
        return $this->sendRequest($query, $bindings, "delete");
        //return parent::delete($query, $bindings); // TODO: Change the autogenerated stub
    }

    public function insert($query, $bindings = [])
    {
        $response = $this->sendRequest($query, $bindings, "insert");
        $this->setLastInsertId(array_get($response, 'lastInsertId', NULL));
        //return parent::insert($query, $bindings); // TODO: Change the autogenerated stub
    }

    public function getLastInsertId()
    {
        return $this->lastInsertId;
    }

    public function setLastInsertId($id)
    {
        if (is_numeric($id)) {
            $id = (int)$id;
        }
        $this->lastInsertId = $id;
    }
}